(()=>{
const DATA=window.MFS_CURRICULUM; const KEY='mfs_sales_academy_progress_v1'; const AUTH_KEY='mfs_sales_academy_auth_v1';
const AUTH={username:'admin',password:'freesample'};
const defaultState=()=>({role:null,view:'learn',roles:{setter:{completed:[],xp:0,activeLesson:null,screen:0},closer:{completed:[],xp:0,activeLesson:null,screen:0}}});
let state=load(); let currentLesson=null; let quizPassed=false;
function load(){try{const x=JSON.parse(localStorage.getItem(KEY)||'null');return x&&x.roles?x:defaultState()}catch(e){return defaultState()}}
function save(){try{localStorage.setItem(KEY,JSON.stringify(state)); if(window.MFSProgressAdapter?.save) window.MFSProgressAdapter.save(state)}catch(e){console.warn(e)}}
const $=s=>document.querySelector(s); const $$=s=>[...document.querySelectorAll(s)];
function path(){return DATA.paths[state.role]||[]}
function roleState(){return state.roles[state.role]}
function flatLessons(){return path().flatMap(m=>m.lessons.map(l=>({...l,moduleId:m.id,moduleTitle:m.title})))}
function isDone(id){return roleState().completed.includes(id)}
function idx(id){return flatLessons().findIndex(l=>l.id===id)}
function prerequisites(id){const i=idx(id);return flatLessons().slice(0,i).filter(l=>!isDone(l.id))}
function unlocked(id){const i=idx(id);return i===0||flatLessons().slice(0,i).every(l=>isDone(l.id))}
function currentId(){return flatLessons().find(l=>!isDone(l.id))?.id||flatLessons().at(-1)?.id}
function readiness(){const all=flatLessons(),foundation=path()[0]?.lessons||[],assessments=all.filter(l=>l.assessment),completed=new Set(roleState().completed);const pct=list=>list.length?Math.round(list.filter(l=>completed.has(l.id)).length/list.length*100):0;const pathPct=pct(all),foundationPct=pct(foundation),checkpointPct=pct(assessments);const score=Math.min(100,Math.round(pathPct*.65+foundationPct*.15+checkpointPct*.20));let status='Foundation in progress',caption='Build the company, offer and buyer fundamentals before moving into live-call execution.';if(score===100){status=state.role==='setter'?'READY TO TAKE SETTER CALLS':'READY TO TAKE CLOSING CALLS';caption='All required lessons and checkpoints are cleared. This rep has completed the academy path.'}else if(score>=90){status='Final certification checks';caption='Almost call-ready. Finish the remaining lessons or checkpoints to clear the path.'}else if(score>=75){status='Nearly call-ready';caption='Core knowledge is strong. The remaining work is mostly execution and certification.'}else if(score>=50){status='Building role readiness';caption='The rep understands the foundation and is now developing role-specific execution.'}else if(score>=25){status='Core knowledge established';caption='Foundation mastery is taking shape. Continue into the role workflow before live calls.'}return{score,status,caption,pathPct,foundationPct,checkpointPct,checkpointsDone:assessments.filter(l=>completed.has(l.id)).length,checkpointsTotal:assessments.length}}
function renderReadiness(){if(!state.role)return;const r=readiness();$$('[data-readiness-card]').forEach(card=>card.classList.toggle('ready',r.score===100));$$('[data-readiness-gauge]').forEach(el=>el.style.setProperty('--readiness',r.score));$$('[data-readiness-score]').forEach(el=>el.textContent=r.score+'%');$$('[data-readiness-status]').forEach(el=>el.textContent=r.status);$$('[data-readiness-caption]').forEach(el=>el.textContent=r.caption);$$('[data-readiness-foundation]').forEach(el=>el.textContent=r.foundationPct+'%');$$('[data-readiness-path]').forEach(el=>el.textContent=r.pathPct+'%');$$('[data-readiness-checkpoints]').forEach(el=>el.textContent=r.checkpointsDone+' / '+r.checkpointsTotal)}
function esc(s){return String(s??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]))}
function shuffle(a){return [...a].map(v=>[Math.random(),v]).sort((a,b)=>a[0]-b[0]).map(x=>x[1])}
function toast(t){const el=$('#toast');el.textContent=t;el.hidden=false;clearTimeout(toast.t);toast.t=setTimeout(()=>el.hidden=true,2200)}
function isAuthenticated(){return localStorage.getItem(AUTH_KEY)==='1'}
function showLogin(){ $('#loginGate').hidden=false; $('#roleGate').hidden=true; $('#appShell').hidden=true; $('#lessonOverlay').hidden=true; $('#challengeModal').hidden=true; document.body.style.overflow=''; setTimeout(()=>$('#loginUsername')?.focus(),50)}
function enterAcademy(){ $('#loginGate').hidden=true; if(state.role){$('#roleGate').hidden=true;$('#appShell').hidden=false;renderAll();const rs=roleState();if(rs.activeLesson&&!isDone(rs.activeLesson))openLesson(rs.activeLesson,rs.screen||0,true)}else showRoleGate()}
function login(e){e.preventDefault();const u=$('#loginUsername').value.trim(),p=$('#loginPassword').value;const err=$('#loginError');if(u===AUTH.username&&p===AUTH.password){localStorage.setItem(AUTH_KEY,'1');err.hidden=true;$('#loginPassword').value='';enterAcademy()}else{err.hidden=false;$('#loginPassword').value='';$('#loginPassword').focus()}}
function logout(){localStorage.removeItem(AUTH_KEY);showLogin()}
function chooseRole(role){state.role=role;state.view='learn';save();$('#roleGate').hidden=true;$('#appShell').hidden=false;renderAll();const rs=roleState();if(rs.activeLesson&&!isDone(rs.activeLesson))openLesson(rs.activeLesson,rs.screen||0,true)}
function showRoleGate(){ $('#loginGate').hidden=true; $('#roleGate').hidden=false; $('#appShell').hidden=true; }
function switchRole(){showRoleGate()}
function setView(view){state.view=view;save();$$('.page').forEach(x=>x.classList.remove('active'));$('#page-'+view).classList.add('active');$$('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===view));if(view==='progress')renderProgress();if(view==='learn')setTimeout(scrollCurrent,80)}
function renderAll(){if(!state.role)return showRoleGate();$('#sideRole').textContent=state.role==='setter'?'Appointment Setter path':'Closer path';$('#mobileRole').textContent=state.role==='setter'?'Setter':'Closer';$('#sidePathName').textContent=state.role==='setter'?'Appointment Setter':'Closer';$('#pathTitle').textContent=state.role==='setter'?'Appointment Setter Path':'Closer Path';$('#pathSubtitle').textContent=state.role==='setter'?'Qualify, book and hand off — one lesson at a time.':'Discover, pitch, close and fulfill — one lesson at a time.';$('#sourceVersion').textContent=DATA.sourceVersion;renderPath();renderGlossary();renderResources();renderProgress();setView(state.view||'learn')}
function renderPath(){const rs=roleState(), all=flatLessons(), done=rs.completed.length, pct=all.length?Math.round(done/all.length*100):0;$('#xpValue').textContent=rs.xp;$('#mobileXP').textContent=rs.xp;$('#progressLabel').textContent=pct+'% complete';$('#progressCount').textContent=done+' / '+all.length+' lessons';$('#progressBar').style.width=pct+'%';renderReadiness();const root=$('#pathList');root.innerHTML='';let num=0;path().forEach((m,mi)=>{const wrap=document.createElement('section');wrap.className='unit-card';let stones='';m.lessons.forEach((l,li)=>{num++;const done=isDone(l.id),un=unlocked(l.id),cur=l.id===currentId()&&!done;stones+=`<div class="stone ${done?'done':''} ${un?'unlocked':'locked'} ${cur?'current':''} ${l.assessment?'assessment':''}" data-lesson-row="${l.id}"><div class="stone-copy"><button data-open-lesson="${l.id}">${esc(l.title)}</button><small>${l.assessment?'CHECKPOINT':l.minutes+' MIN'} ${done?'• COMPLETE':un?'• READY':'• LOCKED'}</small><em class="${!un?'lock-note':''}">${!un?'Tap to test out':esc(l.summary)}</em></div><button class="stone-btn" data-open-lesson="${l.id}" aria-label="Open ${esc(l.title)}">${done?'✓':un?l.icon:'🔒'}</button></div>`});wrap.innerHTML=`<div class="unit-head" data-accent="${m.accent||'green'}"><span class="unit-kicker">UNIT ${mi+1}</span><h3>${esc(m.title)}</h3><p>${esc(m.subtitle)}</p></div><div class="road">${stones}</div>`;root.appendChild(wrap)});$$('[data-open-lesson]').forEach(b=>b.onclick=()=>requestLesson(b.dataset.openLesson));setTimeout(scrollCurrent,60)}
function scrollCurrent(){const el=document.querySelector('.stone.current'); if(el) el.scrollIntoView({behavior:'smooth',block:'center'})}
function requestLesson(id){const pre=prerequisites(id);if(pre.length) return openChallenge(id,pre);openLesson(id,0)}
function getLesson(id){return flatLessons().find(l=>l.id===id)}
function openLesson(id,screen=0,resume=false){currentLesson=getLesson(id);if(!currentLesson)return;roleState().activeLesson=id;roleState().screen=Math.max(0,Math.min(screen,currentLesson.screens.length-1));save();$('#lessonOverlay').hidden=false;document.body.style.overflow='hidden';renderLessonScreen();if(!resume)window.scrollTo(0,0)}
function closeLesson(){if(currentLesson){roleState().activeLesson=currentLesson.id;save()}$('#lessonOverlay').hidden=true;document.body.style.overflow='';renderPath()}
function feedbackText(text,prefix){return String(text||'').replace(prefix==='correct'?/^\s*Correct\.\s*/i:/^\s*Not quite\.\s*/i,'').trim()}
function previousScreen(){const rs=roleState();if(!currentLesson||rs.screen<=0)return;rs.screen--;save();renderLessonScreen();document.querySelector('.lesson-overlay').scrollTo({top:0,behavior:'smooth'})}
function backButton(){return roleState().screen>0?'<button class="btn secondary" id="prevScreen">← Back</button>':''}
function bindBack(){const b=$('#prevScreen');if(b)b.onclick=previousScreen}
function renderLessonScreen(){
  const rs=roleState(),screen=currentLesson.screens[rs.screen],total=currentLesson.screens.length,pct=Math.round((rs.screen)/Math.max(1,total-1)*100);
  $('#lessonProgress').style.width=pct+'%';$('#lessonXP').textContent=rs.xp;quizPassed=false;
  const stage=$('#lessonStage');
  if(screen.type==='lesson'){
    stage.innerHTML=`<article class="lesson-card"><span class="eyebrow">${esc(screen.eyebrow||'LEARN')}</span><h2>${esc(screen.title)}</h2><div class="lesson-body">${esc(screen.body)}</div>${screen.cards?.length?`<div class="mini-cards">${screen.cards.map(c=>`<div class="mini"><b>${esc(c.label)}</b><p>${esc(c.text)}</p></div>`).join('')}</div>`:''}<div class="lesson-actions">${backButton()}<button class="btn" id="nextScreen">Continue</button></div></article>`;
    bindBack();$('#nextScreen').onclick=nextScreen;
  }
  else if(screen.type==='intro'){
    stage.innerHTML=`<article class="lesson-card"><span class="eyebrow">${esc(screen.eyebrow||'CHECKPOINT')}</span><h2>${esc(screen.title)}</h2><div class="lesson-body">${esc(screen.body)}</div><div class="lesson-actions">${backButton()}<button class="btn" id="nextScreen">Start checkpoint</button></div></article>`;
    bindBack();$('#nextScreen').onclick=nextScreen;
  }
  else if(screen.type==='quiz'){
    const opts=shuffle(screen.options),correct=screen.options.find(o=>o.correct),quizScreens=currentLesson.screens.filter(s=>s.type==='quiz'),quizIndex=quizScreens.indexOf(screen)+1,isScenario=screen.kind==='scenario';
    stage.innerHTML=`<article class="lesson-card ${isScenario?'scenario-card':''}"><div class="quiz-head"><div class="quiz-title ${isScenario?'scenario-title':''}">${isScenario?'REAL-WORLD SCENARIO':'KNOWLEDGE CHECK'}</div><div class="quiz-count">QUESTION ${quizIndex} OF ${quizScreens.length}</div></div><h2 class="quiz-question">${esc(screen.question)}</h2><div class="mastery-note ${isScenario?'scenario-note':''}"><span>◆</span> ${isScenario?'Choose the best action for a live lead':'Answer correctly to continue'}</div><div class="quiz-options">${opts.map((o,i)=>`<button class="quiz-option" data-option="${i}">${esc(o.text)}</button>`).join('')}</div><div id="quizFeedback"></div><div class="lesson-actions">${backButton()}<button class="btn" id="nextScreen" disabled>${rs.screen===total-1?'Finish':'Continue'}</button></div></article>`;
    bindBack();
    const buttons=$$('.quiz-option');
    buttons.forEach((b,i)=>b.onclick=()=>{
      const o=opts[i];if(b.classList.contains('correct'))return;
      if(o.correct){
        buttons.forEach(x=>x.disabled=true);b.classList.add('correct');
        const why=feedbackText(o.feedback,'correct')||`This matches the current MFS training: ${o.text}`;
        $('#quizFeedback').innerHTML=`<div class="feedback good"><b>Correct.</b><div class="feedback-explain"><b>Why:</b> ${esc(why)}</div></div>`;
        quizPassed=true;$('#nextScreen').disabled=false;
      }else{
        b.disabled=true;b.classList.add('wrong');
        const chosen=feedbackText(o.feedback,'wrong');
        const why=feedbackText(correct?.feedback,'correct')||`The current MFS answer is “${correct?.text||''}.”`;
        const chosenLine=chosen&&!/review the lesson|think about the current/i.test(chosen)?`<div class="feedback-choice">${esc(chosen)}</div>`:'';
        $('#quizFeedback').innerHTML=`<div class="feedback bad"><b>Not quite.</b>${chosenLine}<div class="feedback-explain"><b>Why:</b> The current MFS answer is <strong>“${esc(correct?.text||'')}”</strong>. ${esc(why)}</div>${rs.screen>0?'<button class="feedback-review" id="reviewPrevious">← Review previous screen</button>':''}<div class="feedback-hint">You can review the material or choose another answer now. You still need the correct answer to continue.</div></div>`;
        const review=$('#reviewPrevious');if(review)review.onclick=previousScreen;
      }
    });
    $('#nextScreen').onclick=nextScreen;
  }
  else if(screen.type==='complete'){
    stage.innerHTML=`<article class="lesson-card"><div class="complete-burst"><div class="big">🏆</div><h2>${esc(screen.title||'Lesson complete')}</h2><p>${esc(screen.body||'Nice work.')}</p><div class="lesson-actions centered">${backButton()}<button class="btn" id="nextScreen">Finish</button></div></div></article>`;
    bindBack();$('#nextScreen').onclick=()=>completeLesson(currentLesson);
  }
}
function nextScreen(){const rs=roleState();if(rs.screen<currentLesson.screens.length-1){rs.screen++;save();renderLessonScreen();document.querySelector('.lesson-overlay').scrollTo({top:0,behavior:'smooth'})}else completeLesson(currentLesson)}
function completeLesson(l){const rs=roleState();if(!rs.completed.includes(l.id)){rs.completed.push(l.id);rs.xp+=l.assessment?150:75;toast(l.assessment?'Checkpoint cleared +150 XP':'Lesson complete +75 XP')}rs.activeLesson=null;rs.screen=0;save();$('#lessonOverlay').hidden=true;document.body.style.overflow='';currentLesson=null;renderAll();setView('learn')}
function quizBank(l){return l.screens.filter(s=>s.type==='quiz').map(q=>({lesson:l,q}))}
function openChallenge(targetId,pre){const modal=$('#challengeModal'),card=$('#challengeCard');const bank=pre.flatMap(quizBank);card.innerHTML=`<span class="pill">TEST OUT</span><h2>Prove you already know it.</h2><p>You are skipping <b>${pre.length}</b> required lesson${pre.length===1?'':'s'}, so this challenge includes <b>${bank.length}</b> question${bank.length===1?'':'s'} from the material you are bypassing. Get every answer right in one attempt to unlock the jump. No XP is awarded for skipped lessons.</p><form id="challengeForm">${bank.map((item,qi)=>`<div class="challenge-q"><div class="challenge-meta">${esc(item.lesson.title)} · ${qi+1}/${bank.length}</div><h4>${esc(item.q.question)}</h4>${shuffle(item.q.options).map((o,oi)=>`<label><input type="radio" name="cq${qi}" value="${o.correct?'1':'0'}" required><span>${esc(o.text)}</span></label>`).join('')}</div>`).join('')}<div id="challengeResult"></div><div class="challenge-actions"><button type="button" class="btn secondary" id="cancelChallenge">Stay on path</button><button class="btn" type="submit">Grade challenge</button></div></form>`;modal.hidden=false;$('#cancelChallenge').onclick=()=>modal.hidden=true;$('#challengeForm').onsubmit=e=>{e.preventDefault();let right=0;const fd=new FormData(e.target);bank.forEach((_,i)=>{if(fd.get('cq'+i)==='1')right++});const res=$('#challengeResult');if(right===bank.length){pre.forEach(l=>{if(!roleState().completed.includes(l.id))roleState().completed.push(l.id)});save();res.innerHTML=`<div class="challenge-result good"><b>${right}/${bank.length}. Perfect score.</b><br>You proved the prerequisites. Opening the lesson…</div>`;setTimeout(()=>{modal.hidden=true;renderPath();openLesson(targetId,0)},500)}else{res.innerHTML=`<div class="challenge-result bad"><b>${right}/${bank.length} correct.</b><br>You need 100% to skip. The correct answers are not shown — review the path or retake the challenge.</div>`;res.scrollIntoView({behavior:'smooth',block:'center'})}}}
function renderGlossary(filter=''){const f=filter.trim().toLowerCase();const arr=DATA.glossary.filter(x=>!f||x.term.toLowerCase().includes(f)||x.definition.toLowerCase().includes(f));$('#glossaryList').innerHTML=arr.map(x=>`<article class="term-card"><h3>${esc(x.term)}</h3><p>${esc(x.definition)}</p></article>`).join('')||'<p>No matching terms.</p>'}
function renderResources(filter=''){const role=state.role;const entries=Object.entries(DATA.resources).filter(([name])=>role==='closer'||!name.startsWith('Fathom Call'));$('#resourceLinks').innerHTML=entries.map(([name,url])=>`<a class="resource-link" href="${esc(url)}" target="_blank" rel="noopener"><b>${esc(name)}</b><span>↗</span></a>`).join('');renderSops(filter)}
function renderSops(filter=''){const f=filter.trim().toLowerCase();let rows=DATA.sops.filter(s=>state.role==='setter'?s.for!=='Closers':s.for!=='Setters');if(f)rows=rows.filter(s=>(s.id+' '+s.title+' '+s.for).toLowerCase().includes(f));$('#sopList').innerHTML=rows.map(s=>`<div class="sop-row"><b>${esc(s.id)}</b><span>${esc(s.title)}</span><em>${esc(s.for)}</em></div>`).join('')}
function renderProgress(){if(!state.role)return;const rs=roleState(),all=flatLessons(),done=rs.completed.length,assess=all.filter(l=>l.assessment&&isDone(l.id)).length,pct=all.length?Math.round(done/all.length*100):0;$('#progressXP').textContent=rs.xp;$('#progressLessons').textContent=done;$('#progressAssessments').textContent=assess;$('#progressPercent').textContent=pct+'%';renderReadiness()}
function resetProgress(){if(!confirm('Reset progress for this role on this device?'))return;state.roles[state.role]={completed:[],xp:0,activeLesson:null,screen:0};save();renderAll();toast('Progress reset')}
$('#loginForm').onsubmit=login;$('#logoutBtn').onclick=logout;$('#mobileLogoutBtn').onclick=logout;$$('[data-role-choice]').forEach(b=>b.onclick=()=>chooseRole(b.dataset.roleChoice));$$('[data-view]').forEach(b=>b.onclick=()=>setView(b.dataset.view));$('#switchRoleBtn').onclick=switchRole;$('#closeLesson').onclick=closeLesson;$('#resetProgressBtn').onclick=resetProgress;$('#glossarySearch').addEventListener('input',e=>renderGlossary(e.target.value));$('#sopSearch').addEventListener('input',e=>renderSops(e.target.value));
window.addEventListener('keydown',e=>{if(e.key==='Escape'){if(!$('#challengeModal').hidden)$('#challengeModal').hidden=true;else if(!$('#lessonOverlay').hidden)closeLesson()}});
if('serviceWorker' in navigator){window.addEventListener('load',()=>navigator.serviceWorker.register('./service-worker.js').catch(()=>{}))}
if(isAuthenticated())enterAcademy();else showLogin();
})();