(()=>{
const DATA=window.MFS_CURRICULUM; const KEY='mfs_sales_academy_progress_v1'; const AUTH_KEY='mfs_sales_academy_auth_v1';
const AUTH={username:'admin',password:'freesample'};
const defaultState=()=>({role:null,view:'learn',roles:{setter:{completed:[],xp:0,activeLesson:null,screen:0},closer:{completed:[],xp:0,activeLesson:null,screen:0}}});
let state=load(); let currentLesson=null; let quizPassed=false;
function load(){try{const x=JSON.parse(localStorage.getItem(KEY)||'null');return x&&x.roles?x:defaultState()}catch(e){return defaultState()}}
function save(){try{localStorage.setItem(KEY,JSON.stringify(state)); if(window.MFSProgressAdapter?.save) window.MFSProgressAdapter.save(state)}catch(e){console.warn(e)}}
const $=s=>document.querySelector(s); const $$=s=>[...document.querySelectorAll(s)];
function path(){return DATA.paths[state.role]||[]}
function roleState(){return state.roles[state.role]}
function flatLessons(){return path().flatMap(m=>m.lessons.map(l=>({...l,moduleId:m.id,moduleTitle:m.title})))}
function isDone(id){return roleState().completed.includes(id)}
function idx(id){return flatLessons().findIndex(l=>l.id===id)}
function prerequisites(id){const i=idx(id);return flatLessons().slice(0,i).filter(l=>!isDone(l.id))}
function unlocked(id){const i=idx(id);return i===0||flatLessons().slice(0,i).every(l=>isDone(l.id))}
function currentId(){return flatLessons().find(l=>!isDone(l.id))?.id||flatLessons().at(-1)?.id}
function esc(s){return String(s??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]))}
function shuffle(a){return [...a].map(v=>[Math.random(),v]).sort((a,b)=>a[0]-b[0]).map(x=>x[1])}
function toast(t){const el=$('#toast');el.textContent=t;el.hidden=false;clearTimeout(toast.t);toast.t=setTimeout(()=>el.hidden=true,2200)}
function isAuthenticated(){return localStorage.getItem(AUTH_KEY)==='1'}
function showLogin(){ $('#loginGate').hidden=false; $('#roleGate').hidden=true; $('#appShell').hidden=true; $('#lessonOverlay').hidden=true; $('#challengeModal').hidden=true; document.body.style.overflow=''; setTimeout(()=>$('#loginUsername')?.focus(),50)}
function enterAcademy(){ $('#loginGate').hidden=true; if(state.role){$('#roleGate').hidden=true;$('#appShell').hidden=false;renderAll();const rs=roleState();if(rs.activeLesson&&!isDone(rs.activeLesson))openLesson(rs.activeLesson,rs.screen||0,true)}else showRoleGate()}
function login(e){e.preventDefault();const u=$('#loginUsername').value.trim(),p=$('#loginPassword').value;const err=$('#loginError');if(u===AUTH.username&&p===AUTH.password){localStorage.setItem(AUTH_KEY,'1');err.hidden=true;$('#loginPassword').value='';enterAcademy()}else{err.hidden=false;$('#loginPassword').value='';$('#loginPassword').focus()}}
function logout(){localStorage.removeItem(AUTH_KEY);showLogin()}
function chooseRole(role){state.role=role;state.view='learn';save();$('#roleGate').hidden=true;$('#appShell').hidden=false;renderAll();const rs=roleState();if(rs.activeLesson&&!isDone(rs.activeLesson))openLesson(rs.activeLesson,rs.screen||0,true)}
function showRoleGate(){ $('#loginGate').hidden=true; $('#roleGate').hidden=false; $('#appShell').hidden=true; }
function switchRole(){showRoleGate()}
function setView(view){state.view=view;save();$$('.page').forEach(x=>x.classList.remove('active'));$('#page-'+view).classList.add('active');$$('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===view));if(view==='progress')renderProgress();if(view==='learn')setTimeout(scrollCurrent,80)}
function renderAll(){if(!state.role)return showRoleGate();$('#sideRole').textContent=state.role==='setter'?'Appointment Setter path':'Closer path';$('#mobileRole').textContent=state.role==='setter'?'Setter':'Closer';$('#sidePathName').textContent=state.role==='setter'?'Appointment Setter':'Closer';$('#pathTitle').textContent=state.role==='setter'?'Appointment Setter Path':'Closer Path';$('#pathSubtitle').textContent=state.role==='setter'?'Qualify, book and hand off — one lesson at a time.':'Discover, pitch, close and fulfill — one lesson at a time.';$('#sourceVersion').textContent=DATA.sourceVersion;renderPath();renderGlossary();renderResources();renderProgress();setView(state.view||'learn')}
function renderPath(){const rs=roleState(), all=flatLessons(), done=rs.completed.length, pct=all.length?Math.round(done/all.length*100):0;$('#xpValue').textContent=rs.xp;$('#mobileXP').textContent=rs.xp;$('#progressLabel').textContent=pct+'% complete';$('#progressCount').textContent=done+' / '+all.length+' lessons';$('#progressBar').style.width=pct+'%';const root=$('#pathList');root.innerHTML='';let num=0;path().forEach((m,mi)=>{const wrap=document.createElement('section');wrap.className='unit-card';let stones='';m.lessons.forEach((l,li)=>{num++;const done=isDone(l.id),un=unlocked(l.id),cur=l.id===currentId()&&!done;stones+=`<div class="stone ${done?'done':''} ${un?'unlocked':'locked'} ${cur?'current':''} ${l.assessment?'assessment':''}" data-lesson-row="${l.id}"><div class="stone-copy"><button data-open-lesson="${l.id}">${esc(l.title)}</button><small>${l.assessment?'CHECKPOINT':l.minutes+' MIN'} ${done?'• COMPLETE':un?'• READY':'• LOCKED'}</small><em class="${!un?'lock-note':''}">${!un?'Tap to test out':esc(l.summary)}</em></div><button class="stone-btn" data-open-lesson="${l.id}" aria-label="Open ${esc(l.title)}">${done?'✓':un?l.icon:'🔒'}</button></div>`});wrap.innerHTML=`<div class="unit-head" data-accent="${m.accent||'green'}"><span class="unit-kicker">UNIT ${mi+1}</span><h3>${esc(m.title)}</h3><p>${esc(m.subtitle)}</p></div><div class="road">${stones}</div>`;root.appendChild(wrap)});$$('[data-open-lesson]').forEach(b=>b.onclick=()=>requestLesson(b.dataset.openLesson));setTimeout(scrollCurrent,60)}
function scrollCurrent(){const el=document.querySelector('.stone.current'); if(el) el.scrollIntoView({behavior:'smooth',block:'center'})}
function requestLesson(id){const pre=prerequisites(id);if(pre.length) return openChallenge(id,pre);openLesson(id,0)}
function getLesson(id){return flatLessons().find(l=>l.id===id)}
function openLesson(id,screen=0,resume=false){currentLesson=getLesson(id);if(!currentLesson)return;roleState().activeLesson=id;roleState().screen=Math.max(0,Math.min(screen,currentLesson.screens.length-1));save();$('#lessonOverlay').hidden=false;document.body.style.overflow='hidden';renderLessonScreen();if(!resume)window.scrollTo(0,0)}
function closeLesson(){if(currentLesson){roleState().activeLesson=currentLesson.id;save()}$('#lessonOverlay').hidden=true;document.body.style.overflow='';renderPath()}
function renderLessonScreen(){const rs=roleState(),screen=currentLesson.screens[rs.screen],total=currentLesson.screens.length,pct=Math.round((rs.screen)/Math.max(1,total-1)*100);$('#lessonProgress').style.width=pct+'%';$('#lessonXP').textContent=rs.xp;quizPassed=false;const stage=$('#lessonStage'); if(screen.type==='lesson'){stage.innerHTML=`<article class="lesson-card"><span class="eyebrow">${esc(screen.eyebrow||'LEARN')}</span><h2>${esc(screen.title)}</h2><div class="lesson-body">${esc(screen.body)}</div>${screen.cards?.length?`<div class="mini-cards">${screen.cards.map(c=>`<div class="mini"><b>${esc(c.label)}</b><p>${esc(c.text)}</p></div>`).join('')}</div>`:''}<div class="lesson-actions"><button class="btn" id="nextScreen">Continue</button></div></article>`;$('#nextScreen').onclick=nextScreen}
else if(screen.type==='intro'){stage.innerHTML=`<article class="lesson-card"><span class="eyebrow">${esc(screen.eyebrow||'CHECKPOINT')}</span><h2>${esc(screen.title)}</h2><div class="lesson-body">${esc(screen.body)}</div><div class="lesson-actions"><button class="btn" id="nextScreen">Start checkpoint</button></div></article>`;$('#nextScreen').onclick=nextScreen}
else if(screen.type==='quiz'){const opts=shuffle(screen.options);stage.innerHTML=`<article class="lesson-card"><div class="quiz-title">KNOWLEDGE CHECK</div><h2 class="quiz-question">${esc(screen.question)}</h2><div class="quiz-options">${opts.map((o,i)=>`<button class="quiz-option" data-option="${i}">${esc(o.text)}</button>`).join('')}</div><div id="quizFeedback"></div><div class="lesson-actions"><button class="btn" id="nextScreen" disabled>${rs.screen===total-1?'Finish':'Continue'}</button></div></article>`;const buttons=$$('.quiz-option');buttons.forEach((b,i)=>b.onclick=()=>{const o=opts[i];if(b.classList.contains('correct'))return;if(o.correct){buttons.forEach(x=>x.disabled=true);b.classList.add('correct');$('#quizFeedback').innerHTML=`<div class="feedback good">${esc(o.feedback||'Correct.')}</div>`;quizPassed=true;$('#nextScreen').disabled=false}else{b.disabled=true;b.classList.add('wrong');$('#quizFeedback').innerHTML=`<div class="feedback bad">${esc(o.feedback||'Not quite. Try again.')}</div>`}});$('#nextScreen').onclick=nextScreen}
else if(screen.type==='complete'){stage.innerHTML=`<article class="lesson-card"><div class="complete-burst"><div class="big">🏆</div><h2>${esc(screen.title||'Lesson complete')}</h2><p>${esc(screen.body||'Nice work.')}</p><button class="btn" id="nextScreen">Finish</button></div></article>`;$('#nextScreen').onclick=()=>completeLesson(currentLesson)} }
function nextScreen(){const rs=roleState();if(rs.screen<currentLesson.screens.length-1){rs.screen++;save();renderLessonScreen();document.querySelector('.lesson-overlay').scrollTo({top:0,behavior:'smooth'})}else completeLesson(currentLesson)}
function completeLesson(l){const rs=roleState();if(!rs.completed.includes(l.id)){rs.completed.push(l.id);rs.xp+=l.assessment?150:75;toast(l.assessment?'Checkpoint cleared +150 XP':'Lesson complete +75 XP')}rs.activeLesson=null;rs.screen=0;save();$('#lessonOverlay').hidden=true;document.body.style.overflow='';currentLesson=null;renderAll();setView('learn')}
function firstQuiz(l){return l.screens.find(s=>s.type==='quiz')}
function openChallenge(targetId,pre){const modal=$('#challengeModal'),card=$('#challengeCard');const bank=pre.map(l=>({lesson:l,q:firstQuiz(l)})).filter(x=>x.q);card.innerHTML=`<span class="pill">TEST OUT</span><h2>Want to jump ahead?</h2><p>You are skipping <b>${bank.length}</b> required lesson${bank.length===1?'':'s'}. Get every question right in one attempt and the skipped lessons will be marked complete. No XP is awarded for skipped lessons.</p><form id="challengeForm">${bank.map((item,qi)=>`<div class="challenge-q"><h4>${qi+1}. ${esc(item.q.question)}</h4>${shuffle(item.q.options).map((o,oi)=>`<label><input type="radio" name="cq${qi}" value="${o.correct?'1':'0'}" required><span>${esc(o.text)}</span></label>`).join('')}</div>`).join('')}<div id="challengeResult"></div><div class="challenge-actions"><button type="button" class="btn secondary" id="cancelChallenge">Stay on path</button><button class="btn" type="submit">Grade challenge</button></div></form>`;modal.hidden=false;$('#cancelChallenge').onclick=()=>modal.hidden=true;$('#challengeForm').onsubmit=e=>{e.preventDefault();let right=0;bank.forEach((_,i)=>{const v=new FormData(e.target).get('cq'+i);if(v==='1')right++});const res=$('#challengeResult');if(right===bank.length){pre.forEach(l=>{if(!roleState().completed.includes(l.id))roleState().completed.push(l.id)});save();res.innerHTML=`<div class="challenge-result good"><b>${right}/${bank.length}. Perfect score.</b><br>You proved the prerequisites. Opening the lesson…</div>`;setTimeout(()=>{modal.hidden=true;renderPath();openLesson(targetId,0)},500)}else{res.innerHTML=`<div class="challenge-result bad"><b>${right}/${bank.length} correct.</b><br>You need 100% to skip. The correct answers are not shown — review the path or retake the challenge.</div>`;res.scrollIntoView({behavior:'smooth',block:'center'})}}}
function renderGlossary(filter=''){const f=filter.trim().toLowerCase();const arr=DATA.glossary.filter(x=>!f||x.term.toLowerCase().includes(f)||x.definition.toLowerCase().includes(f));$('#glossaryList').innerHTML=arr.map(x=>`<article class="term-card"><h3>${esc(x.term)}</h3><p>${esc(x.definition)}</p></article>`).join('')||'<p>No matching terms.</p>'}
function renderResources(filter=''){const role=state.role;const entries=Object.entries(DATA.resources).filter(([name])=>role==='closer'||!name.startsWith('Fathom Call'));$('#resourceLinks').innerHTML=entries.map(([name,url])=>`<a class="resource-link" href="${esc(url)}" target="_blank" rel="noopener"><b>${esc(name)}</b><span>↗</span></a>`).join('');renderSops(filter)}
function renderSops(filter=''){const f=filter.trim().toLowerCase();let rows=DATA.sops.filter(s=>state.role==='setter'?s.for!=='Closers':s.for!=='Setters');if(f)rows=rows.filter(s=>(s.id+' '+s.title+' '+s.for).toLowerCase().includes(f));$('#sopList').innerHTML=rows.map(s=>`<div class="sop-row"><b>${esc(s.id)}</b><span>${esc(s.title)}</span><em>${esc(s.for)}</em></div>`).join('')}
function renderProgress(){if(!state.role)return;const rs=roleState(),all=flatLessons(),done=rs.completed.length,assess=all.filter(l=>l.assessment&&isDone(l.id)).length,pct=all.length?Math.round(done/all.length*100):0;$('#progressXP').textContent=rs.xp;$('#progressLessons').textContent=done;$('#progressAssessments').textContent=assess;$('#progressPercent').textContent=pct+'%'}
function resetProgress(){if(!confirm('Reset progress for this role on this device?'))return;state.roles[state.role]={completed:[],xp:0,activeLesson:null,screen:0};save();renderAll();toast('Progress reset')}
$('#loginForm').onsubmit=login;$('#logoutBtn').onclick=logout;$('#mobileLogoutBtn').onclick=logout;$$('[data-role-choice]').forEach(b=>b.onclick=()=>chooseRole(b.dataset.roleChoice));$$('[data-view]').forEach(b=>b.onclick=()=>setView(b.dataset.view));$('#switchRoleBtn').onclick=switchRole;$('#closeLesson').onclick=closeLesson;$('#resetProgressBtn').onclick=resetProgress;$('#glossarySearch').addEventListener('input',e=>renderGlossary(e.target.value));$('#sopSearch').addEventListener('input',e=>renderSops(e.target.value));
window.addEventListener('keydown',e=>{if(e.key==='Escape'){if(!$('#challengeModal').hidden)$('#challengeModal').hidden=true;else if(!$('#lessonOverlay').hidden)closeLesson()}});
if('serviceWorker' in navigator){window.addEventListener('load',()=>navigator.serviceWorker.register('./service-worker.js').catch(()=>{}))}
if(isAuthenticated())enterAcademy();else showLogin();
})();